#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuildingAmbienceManager

#include "Basic.hpp"

#include "BP_BuildingAmbienceManager_classes.hpp"
#include "BP_BuildingAmbienceManager_parameters.hpp"


namespace SDK
{

// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.ExecuteUbergraph_BP_BuildingAmbienceManager
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BuildingAmbienceManager_C::ExecuteUbergraph_BP_BuildingAmbienceManager(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "ExecuteUbergraph_BP_BuildingAmbienceManager");

	Params::BP_BuildingAmbienceManager_C_ExecuteUbergraph_BP_BuildingAmbienceManager Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.FindNearestBuildingAmbienceActor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Building_Caller_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class ABP_BuildingAmbienceActor_C**     Closest_Actor_0                                        (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_BuildingAmbienceManager_C::FindNearestBuildingAmbienceActor(class AActor* Building_Caller_0, class ABP_BuildingAmbienceActor_C** Closest_Actor_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "FindNearestBuildingAmbienceActor");

	Params::BP_BuildingAmbienceManager_C_FindNearestBuildingAmbienceActor Parms{};

	Parms.Building_Caller_0 = Building_Caller_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Closest_Actor_0 != nullptr)
		*Closest_Actor_0 = Parms.Closest_Actor_0;
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.FindStructuresWithinRange
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_BuildingAmbienceActor_C*      Actor_Location                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FVector>*                 Structures_In_Range                                    (Parm, OutParm)

void ABP_BuildingAmbienceManager_C::FindStructuresWithinRange(class ABP_BuildingAmbienceActor_C* Actor_Location, TArray<struct FVector>* Structures_In_Range)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "FindStructuresWithinRange");

	Params::BP_BuildingAmbienceManager_C_FindStructuresWithinRange Parms{};

	Parms.Actor_Location = Actor_Location;

	UObject::ProcessEvent(Func, &Parms);

	if (Structures_In_Range != nullptr)
		*Structures_In_Range = std::move(Parms.Structures_In_Range);
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.PopulateBuildingAmbience
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Building_Actor_Input                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Debug_Ambience_Population_0                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    Debug_Print_Data_0                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_BuildingAmbienceActor_C**     Building_Ambience_Actor                                (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  Building_Count                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BuildingAmbienceManager_C::PopulateBuildingAmbience(class AActor* Building_Actor_Input, bool Debug_Ambience_Population_0, bool Debug_Print_Data_0, class ABP_BuildingAmbienceActor_C** Building_Ambience_Actor, int32* Building_Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "PopulateBuildingAmbience");

	Params::BP_BuildingAmbienceManager_C_PopulateBuildingAmbience Parms{};

	Parms.Building_Actor_Input = Building_Actor_Input;
	Parms.Debug_Ambience_Population_0 = Debug_Ambience_Population_0;
	Parms.Debug_Print_Data_0 = Debug_Print_Data_0;

	UObject::ProcessEvent(Func, &Parms);

	if (Building_Ambience_Actor != nullptr)
		*Building_Ambience_Actor = Parms.Building_Ambience_Actor;

	if (Building_Count != nullptr)
		*Building_Count = Parms.Building_Count;
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.RecalculateBuildingAmbience
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Building_Caller_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    Debug_on_Destroyed                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABP_BuildingAmbienceActor_C**     Building_Ambience_Actor                                (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  Building_Count                                         (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BuildingAmbienceManager_C::RecalculateBuildingAmbience(class AActor* Building_Caller_0, bool Debug_on_Destroyed, class ABP_BuildingAmbienceActor_C** Building_Ambience_Actor, int32* Building_Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "RecalculateBuildingAmbience");

	Params::BP_BuildingAmbienceManager_C_RecalculateBuildingAmbience Parms{};

	Parms.Building_Caller_0 = Building_Caller_0;
	Parms.Debug_on_Destroyed = Debug_on_Destroyed;

	UObject::ProcessEvent(Func, &Parms);

	if (Building_Ambience_Actor != nullptr)
		*Building_Ambience_Actor = Parms.Building_Ambience_Actor;

	if (Building_Count != nullptr)
		*Building_Count = Parms.Building_Count;
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BuildingAmbienceManager_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BuildingAmbienceManager.BP_BuildingAmbienceManager_C.SoundActorDistanceCheck
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Actor_Caller                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   Actor_Too_Close_0                                      (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BuildingAmbienceManager_C::SoundActorDistanceCheck(const struct FVector& Actor_Caller, bool* Actor_Too_Close_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BuildingAmbienceManager_C", "SoundActorDistanceCheck");

	Params::BP_BuildingAmbienceManager_C_SoundActorDistanceCheck Parms{};

	Parms.Actor_Caller = std::move(Actor_Caller);

	UObject::ProcessEvent(Func, &Parms);

	if (Actor_Too_Close_0 != nullptr)
		*Actor_Too_Close_0 = Parms.Actor_Too_Close_0;
}

}

