#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BD_VETI_WarAssembly

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "PhysicsCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function BP_BD_VETI_WarAssembly.BP_BD_VETI_WarAssembly_C.ExecuteUbergraph_BP_BD_VETI_WarAssembly
// 0x0880 (0x0880 - 0x0000)
struct BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0030(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_4;                   // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_HealthPct;                            // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_2;          // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_3;          // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<EObjectTypeQuery>                      K2Node_MakeArray_Array;                            // 0x0048(0x0010)(ConstParm, ReferenceParm)
	class UAnimMontage*                           CallFunc_GetCurrentMontage_ReturnValue;            // 0x0058(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0061(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_62[0x6];                                       // 0x0062(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0068(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0088(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_1;           // 0x00A0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_4;                  // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x00BC(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue_4;                 // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue;            // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_1;              // 0x00F0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_1;          // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_2;              // 0x0108(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_2;          // 0x0118(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_3;              // 0x0120(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_3;          // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_4;              // 0x0138(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_5;              // 0x0148(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_4;          // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_5;          // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bInConstructing;                      // 0x0168(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bBlackedOut;                          // 0x0169(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bUserPowered;                         // 0x016A(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bSufficientPower;                     // 0x016B(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_16C[0x4];                                      // 0x016C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class ATedUnitBase*>                   CallFunc_GetSpawnedUnits_ReturnValue;              // 0x0170(0x0010)(ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0180(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable;                                 // 0x0184(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_189[0x3];                                      // 0x0189(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_5;                 // 0x018C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0190(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue;         // 0x01A8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMaterialInstanceDynamic*               CallFunc_Array_Get_Item;                           // 0x01B8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C4[0x4];                                      // 0x01C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x01C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_Conv_VectorToVector2D_ReturnValue;        // 0x01D0(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemComponent*                     CallFunc_SpawnEffectAtLocation_ReturnValue;        // 0x01E0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetGroundLocation_ReturnValue;            // 0x01E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X;                            // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y;                            // 0x0208(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z;                            // 0x0210(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_X_1;                          // 0x0218(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Y_1;                          // 0x0220(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_BreakVector_Z_1;                          // 0x0228(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0230(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0238(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable_5;                  // 0x0250(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Array_Get_Item_1;                         // 0x0254(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x025C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_25D[0x3];                                      // 0x025D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue_6;                 // 0x0260(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x0264(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0268(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_2;                         // 0x0270(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0278(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x0290(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x0294(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_295[0x3];                                      // 0x0295(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0298(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29C[0x4];                                      // 0x029C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_Array_Get_Item_3;                         // 0x02A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x02A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_4;                // 0x02AC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2AD[0x3];                                      // 0x02AD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x02B0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x02C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x02D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x02E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_4;                         // 0x0300(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_6;               // 0x0308(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_5;                // 0x030C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_30D[0x3];                                      // 0x030D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0310(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_1;         // 0x0318(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_2;         // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_3;         // 0x0328(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue;                  // 0x0330(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	class UStaticMeshComponent*                   CallFunc_Array_Get_Item_5;                         // 0x0348(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetRelativeRotation_SweepHitResult;    // 0x0350(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	int32                                         CallFunc_Array_Length_ReturnValue_7;               // 0x0448(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue_6;                // 0x044C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44D[0x3];                                      // 0x044D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_1;      // 0x0450(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_VEase_ReturnValue;                        // 0x0458(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_K2_SetWorldLocation_SweepHitResult;       // 0x0470(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	double                                        CallFunc_MakeLiteralDouble_ReturnValue;            // 0x0568(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Divide_DoubleDouble_ReturnValue;          // 0x0570(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable_5;                   // 0x0578(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_57C[0x4];                                      // 0x057C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue_1;      // 0x0580(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Array_Get_Item_6;                         // 0x0588(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0598(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_RandomFloatInRange_ReturnValue_4;         // 0x05A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue_6;              // 0x05A8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue_1;        // 0x05B8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   CallFunc_Conv_StringToName_ReturnValue_6;          // 0x05D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue;        // 0x05D8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetScalarParameterValue_ReturnValue;      // 0x05F0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5F4[0x4];                                      // 0x05F4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Multiply_VectorVector_ReturnValue_1;      // 0x05F8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_DoubleDouble_ReturnValue;      // 0x0610(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_611[0x7];                                      // 0x0611(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue_2;           // 0x0618(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0630(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_634[0x4];                                      // 0x0634(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_RandomFloatInRange_ReturnValue_5;         // 0x0638(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               CallFunc_MakeRotator_ReturnValue_1;                // 0x0640(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor)
	struct FVector2D                              CallFunc_Conv_VectorToVector2D_ReturnValue_1;      // 0x0658(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetGroundLocation_ReturnValue_1;          // 0x0668(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue;         // 0x0680(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class AActor*>                         Temp_object_Variable;                              // 0x0688(0x0010)(ConstParm, ReferenceParm)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue_2;      // 0x0698(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FHitResult                             CallFunc_LineTraceSingleForObjects_OutHit;         // 0x06A0(0x00F8)(IsPlainOldData, NoDestructor, ContainsInstancedReference)
	bool                                          CallFunc_LineTraceSingleForObjects_ReturnValue;    // 0x0798(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPhysicalSurface                              CallFunc_GetSurfaceType_ReturnValue;               // 0x0799(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_79A[0x2];                                      // 0x079A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x079C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UStaticMeshComponent*>           K2Node_MakeArray_Array_1;                          // 0x07A0(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UNiagaraComponent*>              K2Node_MakeArray_Array_2;                          // 0x07B0(0x0010)(ReferenceParm, ContainsInstancedReference)
	bool                                          CallFunc_IsFogOfWarVisibleForLocalPlayer_ReturnValue; // 0x07C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x07C1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C2[0x6];                                      // 0x07C2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAtLocation_ReturnValue_1;       // 0x07C8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue_1;    // 0x07D0(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue_2;        // 0x07E8(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UDecalComponent*                        CallFunc_SpawnDecalAtLocation_ReturnValue_1;       // 0x0800(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0808(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0809(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x080A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_80B[0x5];                                      // 0x080B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast;         // 0x0810(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast_1;       // 0x0818(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast_2;       // 0x0820(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Less_DoubleDouble_A_ImplicitCast_3;       // 0x0828(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_LessEqual_DoubleDouble_A_ImplicitCast;    // 0x0830(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast; // 0x0838(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_1; // 0x083C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetFloatParameter_Param_ImplicitCast;     // 0x0840(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Yaw_ImplicitCast;             // 0x0844(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Pitch_ImplicitCast;           // 0x0848(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Roll_ImplicitCast;            // 0x084C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0850(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VEase_Alpha_ImplicitCast;                 // 0x0858(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85C[0x4];                                      // 0x085C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast;   // 0x0860(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MakeRotator_Roll_ImplicitCast_1;          // 0x0868(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_86C[0x4];                                      // 0x086C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1;   // 0x0870(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_2; // 0x0878(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly) == 0x000008, "Wrong alignment on BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly");
static_assert(sizeof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly) == 0x000880, "Wrong size on BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, EntryPoint) == 0x000000, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable) == 0x000008, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable_1) == 0x000014, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable_1) == 0x000018, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_1) == 0x00001C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable_2) == 0x000020, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_2) == 0x000024, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable_2) == 0x000028, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable_3) == 0x00002C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable_3) == 0x000030, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_3) == 0x000034, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable_4) == 0x000038, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_Event_HealthPct) == 0x00003C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_Event_HealthPct' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_LessEqual_DoubleDouble_ReturnValue) == 0x000040, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_LessEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_ReturnValue) == 0x000041, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_ReturnValue_1) == 0x000042, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_ReturnValue_2) == 0x000043, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_ReturnValue_3) == 0x000044, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_MakeArray_Array) == 0x000048, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetCurrentMontage_ReturnValue) == 0x000058, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetCurrentMontage_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_IsDedicatedServer_ReturnValue) == 0x000060, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_IsDedicatedServer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000061, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000068, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_IsDedicatedServer_ReturnValue_1) == 0x000080, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_IsDedicatedServer_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_VectorVector_ReturnValue) == 0x000088, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_VectorVector_ReturnValue_1) == 0x0000A0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable_4) == 0x0000B8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_VectorToLinearColor_ReturnValue) == 0x0000BC, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_VectorToLinearColor_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_4) == 0x0000CC, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue) == 0x0000D0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue) == 0x0000D4, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue) == 0x0000D8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue) == 0x0000E8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_1) == 0x0000F0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_1) == 0x000100, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_2) == 0x000108, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_2) == 0x000118, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_3) == 0x000120, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_3) == 0x000130, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_4) == 0x000138, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_5) == 0x000148, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_4) == 0x000158, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_5) == 0x000160, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_Event_bInConstructing) == 0x000168, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_Event_bInConstructing' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_Event_bBlackedOut) == 0x000169, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_Event_bBlackedOut' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_Event_bUserPowered) == 0x00016A, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_Event_bUserPowered' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_Event_bSufficientPower) == 0x00016B, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_Event_bSufficientPower' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetSpawnedUnits_ReturnValue) == 0x000170, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetSpawnedUnits_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_1) == 0x000180, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Variable) == 0x000184, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000188, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_5) == 0x00018C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000190, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SpawnSoundAtLocation_ReturnValue) == 0x0001A8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SpawnSoundAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_IsValid_ReturnValue_1) == 0x0001B0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item) == 0x0001B8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_2) == 0x0001C0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue) == 0x0001C8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_VectorToVector2D_ReturnValue) == 0x0001D0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_VectorToVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SpawnEffectAtLocation_ReturnValue) == 0x0001E0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SpawnEffectAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetGroundLocation_ReturnValue) == 0x0001E8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetGroundLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_X) == 0x000200, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_X' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_Y) == 0x000208, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_Y' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_Z) == 0x000210, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_Z' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_X_1) == 0x000218, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_X_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_Y_1) == 0x000220, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_Y_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BreakVector_Z_1) == 0x000228, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BreakVector_Z_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Subtract_DoubleDouble_ReturnValue) == 0x000230, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Subtract_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetSocketLocation_ReturnValue) == 0x000238, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Loop_Counter_Variable_5) == 0x000250, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Loop_Counter_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_1) == 0x000254, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_1) == 0x00025C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_IntInt_ReturnValue_6) == 0x000260, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_3) == 0x000264, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_2) == 0x000268, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_2) == 0x000270, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000278, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_4) == 0x000290, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_3) == 0x000294, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Add_ReturnValue) == 0x000298, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_3) == 0x0002A0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_5) == 0x0002A8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_4) == 0x0002AC, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Subtract_VectorVector_ReturnValue) == 0x0002B0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Subtract_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_VSize_ReturnValue) == 0x0002C8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Normal_ReturnValue) == 0x0002D0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_DoubleToVector_ReturnValue) == 0x0002E8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_DoubleToVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_4) == 0x000300, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_6) == 0x000308, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_5) == 0x00030C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_DoubleDouble_ReturnValue) == 0x000310, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue_1) == 0x000318, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue_2) == 0x000320, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue_3) == 0x000328, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_ReturnValue) == 0x000330, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_5) == 0x000348, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_SetRelativeRotation_SweepHitResult) == 0x000350, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_SetRelativeRotation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Length_ReturnValue_7) == 0x000448, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Length_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_IntInt_ReturnValue_6) == 0x00044C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_IntInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_DoubleDouble_ReturnValue_1) == 0x000450, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_VEase_ReturnValue) == 0x000458, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_VEase_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_SetWorldLocation_SweepHitResult) == 0x000470, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_SetWorldLocation_SweepHitResult' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeLiteralDouble_ReturnValue) == 0x000568, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeLiteralDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Divide_DoubleDouble_ReturnValue) == 0x000570, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Divide_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_int_Array_Index_Variable_5) == 0x000578, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_int_Array_Index_Variable_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Subtract_DoubleDouble_ReturnValue_1) == 0x000580, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Subtract_DoubleDouble_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Get_Item_6) == 0x000588, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Get_Item_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_DoubleDouble_ReturnValue) == 0x000598, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue_4) == 0x0005A0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Concat_StrStr_ReturnValue_6) == 0x0005A8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Concat_StrStr_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_DoubleToVector_ReturnValue_1) == 0x0005B8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_DoubleToVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_StringToName_ReturnValue_6) == 0x0005D0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_StringToName_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_VectorVector_ReturnValue) == 0x0005D8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetScalarParameterValue_ReturnValue) == 0x0005F0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetScalarParameterValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_VectorVector_ReturnValue_1) == 0x0005F8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_EqualEqual_DoubleDouble_ReturnValue) == 0x000610, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_EqualEqual_DoubleDouble_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Add_VectorVector_ReturnValue_2) == 0x000618, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Add_VectorVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Array_Add_ReturnValue_1) == 0x000630, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_RandomFloatInRange_ReturnValue_5) == 0x000638, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_RandomFloatInRange_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_ReturnValue_1) == 0x000640, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_VectorToVector2D_ReturnValue_1) == 0x000658, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_VectorToVector2D_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetGroundLocation_ReturnValue_1) == 0x000668, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetGroundLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SpawnDecalAtLocation_ReturnValue) == 0x000680, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SpawnDecalAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_object_Variable) == 0x000688, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_object_Variable' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_DoubleDouble_ReturnValue_2) == 0x000698, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_DoubleDouble_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_LineTraceSingleForObjects_OutHit) == 0x0006A0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_LineTraceSingleForObjects_OutHit' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_LineTraceSingleForObjects_ReturnValue) == 0x000798, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_LineTraceSingleForObjects_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_GetSurfaceType_ReturnValue) == 0x000799, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_GetSurfaceType_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_ByteToInt_ReturnValue) == 0x00079C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_ByteToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_MakeArray_Array_1) == 0x0007A0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, K2Node_MakeArray_Array_2) == 0x0007B0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::K2Node_MakeArray_Array_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_IsFogOfWarVisibleForLocalPlayer_ReturnValue) == 0x0007C0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_IsFogOfWarVisibleForLocalPlayer_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BooleanAND_ReturnValue) == 0x0007C1, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SpawnSoundAtLocation_ReturnValue_1) == 0x0007C8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SpawnSoundAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_K2_GetComponentLocation_ReturnValue_1) == 0x0007D0, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_K2_GetComponentLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Conv_DoubleToVector_ReturnValue_2) == 0x0007E8, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Conv_DoubleToVector_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SpawnDecalAtLocation_ReturnValue_1) == 0x000800, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SpawnDecalAtLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, Temp_bool_True_if_break_was_hit_Variable) == 0x000808, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Not_PreBool_ReturnValue) == 0x000809, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_BooleanAND_ReturnValue_1) == 0x00080A, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_A_ImplicitCast) == 0x000810, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_A_ImplicitCast_1) == 0x000818, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_A_ImplicitCast_2) == 0x000820, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_A_ImplicitCast_2' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Less_DoubleDouble_A_ImplicitCast_3) == 0x000828, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Less_DoubleDouble_A_ImplicitCast_3' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_LessEqual_DoubleDouble_A_ImplicitCast) == 0x000830, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_LessEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast) == 0x000838, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_1) == 0x00083C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SetFloatParameter_Param_ImplicitCast) == 0x000840, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SetFloatParameter_Param_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_Yaw_ImplicitCast) == 0x000844, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_Yaw_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_Pitch_ImplicitCast) == 0x000848, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_Pitch_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_Roll_ImplicitCast) == 0x00084C, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_Roll_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_DoubleDouble_A_ImplicitCast) == 0x000850, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_VEase_Alpha_ImplicitCast) == 0x000858, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_VEase_Alpha_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast) == 0x000860, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_EqualEqual_DoubleDouble_A_ImplicitCast' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_MakeRotator_Roll_ImplicitCast_1) == 0x000868, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_MakeRotator_Roll_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1) == 0x000870, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_Multiply_DoubleDouble_A_ImplicitCast_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly, CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_2) == 0x000878, "Member 'BP_BD_VETI_WarAssembly_C_ExecuteUbergraph_BP_BD_VETI_WarAssembly::CallFunc_SetScalarParameterValue_ParameterValue_ImplicitCast_2' has a wrong offset!");

// Function BP_BD_VETI_WarAssembly.BP_BD_VETI_WarAssembly_C.K2_OnUnitSpawned
// 0x0080 (0x0080 - 0x0000)
struct BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned final
{
public:
	class ATedUnitBase*                           SpawnedUnit;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ATedUnitBase*                           ReturnValue;                                       // 0x0008(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0010(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x0030(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ABP_VETI_Vehicle_RepairServitor_C*      K2Node_DynamicCast_AsBP_VETI_Vehicle_Repair_Servitor; // 0x0048(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0058(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ATedPlayerController*                   CallFunc_GetOwningPlayerController_ReturnValue;    // 0x0070(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlayerControlled_ReturnValue;           // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocalPlayerController_ReturnValue;      // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned) == 0x000008, "Wrong alignment on BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned");
static_assert(sizeof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned) == 0x000080, "Wrong size on BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, SpawnedUnit) == 0x000000, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::SpawnedUnit' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, ReturnValue) == 0x000008, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_K2_GetActorLocation_ReturnValue) == 0x000010, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_IsValid_ReturnValue) == 0x000028, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_GetSocketLocation_ReturnValue) == 0x000030, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, K2Node_DynamicCast_AsBP_VETI_Vehicle_Repair_Servitor) == 0x000048, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::K2Node_DynamicCast_AsBP_VETI_Vehicle_Repair_Servitor' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_K2_GetActorLocation_ReturnValue_1) == 0x000058, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_K2_GetActorLocation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_GetOwningPlayerController_ReturnValue) == 0x000070, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_GetOwningPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_IsPlayerControlled_ReturnValue) == 0x000078, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_IsPlayerControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_IsLocalPlayerController_ReturnValue) == 0x000079, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_IsLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned, CallFunc_BooleanAND_ReturnValue) == 0x00007A, "Member 'BP_BD_VETI_WarAssembly_C_K2_OnUnitSpawned::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function BP_BD_VETI_WarAssembly.BP_BD_VETI_WarAssembly_C.ReceiveHandleConstructionVisuals
// 0x0001 (0x0001 - 0x0000)
struct BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals final
{
public:
	bool                                          bInConstructing;                                   // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals) == 0x000001, "Wrong alignment on BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals");
static_assert(sizeof(BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals) == 0x000001, "Wrong size on BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals, bInConstructing) == 0x000000, "Member 'BP_BD_VETI_WarAssembly_C_ReceiveHandleConstructionVisuals::bInConstructing' has a wrong offset!");

// Function BP_BD_VETI_WarAssembly.BP_BD_VETI_WarAssembly_C.ReceiveHandlePowerStateVisuals
// 0x0003 (0x0003 - 0x0000)
struct BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals final
{
public:
	bool                                          bBlackedOut;                                       // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bUserPowered;                                      // 0x0001(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bSufficientPower;                                  // 0x0002(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals) == 0x000001, "Wrong alignment on BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals");
static_assert(sizeof(BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals) == 0x000003, "Wrong size on BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals, bBlackedOut) == 0x000000, "Member 'BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals::bBlackedOut' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals, bUserPowered) == 0x000001, "Member 'BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals::bUserPowered' has a wrong offset!");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals, bSufficientPower) == 0x000002, "Member 'BP_BD_VETI_WarAssembly_C_ReceiveHandlePowerStateVisuals::bSufficientPower' has a wrong offset!");

// Function BP_BD_VETI_WarAssembly.BP_BD_VETI_WarAssembly_C.ReceiveUpdateHealthEffects
// 0x0004 (0x0004 - 0x0000)
struct BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects final
{
public:
	float                                         HealthPct;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects) == 0x000004, "Wrong alignment on BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects");
static_assert(sizeof(BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects) == 0x000004, "Wrong size on BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects");
static_assert(offsetof(BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects, HealthPct) == 0x000000, "Member 'BP_BD_VETI_WarAssembly_C_ReceiveUpdateHealthEffects::HealthPct' has a wrong offset!");

}

