#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BD_GDF_HealingTurret

#include "Basic.hpp"

#include "BP_BD_GDF_HealingTurret_classes.hpp"
#include "BP_BD_GDF_HealingTurret_parameters.hpp"


namespace SDK
{

// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.ExecuteUbergraph_BP_BD_GDF_HealingTurret
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_BD_GDF_HealingTurret_C::ExecuteUbergraph_BP_BD_GDF_HealingTurret(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "ExecuteUbergraph_BP_BD_GDF_HealingTurret");

	Params::BP_BD_GDF_HealingTurret_C_ExecuteUbergraph_BP_BD_GDF_HealingTurret Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.OnLifeTimeExpired
// (Event, Protected, BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::OnLifeTimeExpired()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "OnLifeTimeExpired");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.OnLifeTimeExpiredCosmetic
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::OnLifeTimeExpiredCosmetic()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "OnLifeTimeExpiredCosmetic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.ReceiveOnDeath
// (Event, Protected, BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::ReceiveOnDeath()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "ReceiveOnDeath");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_Dial__FinishedFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_Dial__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_Dial__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_Dial__UpdateFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_Dial__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_Dial__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__Explosion__EventFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__Explosion__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__Explosion__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__ExplosionAudio__EventFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__ExplosionAudio__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__ExplosionAudio__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__FinishedFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__FinishedFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__FinishedFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__SpawnChunks__EventFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__SpawnChunks__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__SpawnChunks__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__SpawnDecal__EventFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__SpawnDecal__EventFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__SpawnDecal__EventFunc");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_BD_GDF_HealingTurret.BP_BD_GDF_HealingTurret_C.TL_OnDeath__UpdateFunc
// (BlueprintEvent)

void ABP_BD_GDF_HealingTurret_C::TL_OnDeath__UpdateFunc()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_BD_GDF_HealingTurret_C", "TL_OnDeath__UpdateFunc");

	UObject::ProcessEvent(Func, nullptr);
}

}

