#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CmdPreview_DeployStructure

#include "Basic.hpp"

#include "Tempest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CmdPreview_DeployStructure.BP_CmdPreview_DeployStructure_C
// 0x0000 (0x04A8 - 0x04A8)
class ABP_CmdPreview_DeployStructure_C final : public ATedPawnCommandPreview_DeployStructure
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CmdPreview_DeployStructure_C">();
	}
	static class ABP_CmdPreview_DeployStructure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CmdPreview_DeployStructure_C>();
	}
};
static_assert(alignof(ABP_CmdPreview_DeployStructure_C) == 0x000008, "Wrong alignment on ABP_CmdPreview_DeployStructure_C");
static_assert(sizeof(ABP_CmdPreview_DeployStructure_C) == 0x0004A8, "Wrong size on ABP_CmdPreview_DeployStructure_C");

}

