#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCue_HitActor_MineATVeti

#include "Basic.hpp"

#include "Tempest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCue_HitActor_MineATVeti.GCue_HitActor_MineATVeti_C
// 0x0008 (0x03A0 - 0x0398)
class AGCue_HitActor_MineATVeti_C final : public ATedGameplayCueNotify_HitActor
{
public:
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0398(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	bool OnExecute(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCue_HitActor_MineATVeti_C">();
	}
	static class AGCue_HitActor_MineATVeti_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGCue_HitActor_MineATVeti_C>();
	}
};
static_assert(alignof(AGCue_HitActor_MineATVeti_C) == 0x000008, "Wrong alignment on AGCue_HitActor_MineATVeti_C");
static_assert(sizeof(AGCue_HitActor_MineATVeti_C) == 0x0003A0, "Wrong size on AGCue_HitActor_MineATVeti_C");
static_assert(offsetof(AGCue_HitActor_MineATVeti_C, DefaultSceneRoot) == 0x000398, "Member 'AGCue_HitActor_MineATVeti_C::DefaultSceneRoot' has a wrong offset!");

}

