#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TedAch_YouCantSeeMe

#include "Basic.hpp"

#include "Tempest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TedAch_YouCantSeeMe.TedAch_YouCantSeeMe_C
// 0x0000 (0x0070 - 0x0070)
class UTedAch_YouCantSeeMe_C final : public UTedAchievementEntry
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TedAch_YouCantSeeMe_C">();
	}
	static class UTedAch_YouCantSeeMe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTedAch_YouCantSeeMe_C>();
	}
};
static_assert(alignof(UTedAch_YouCantSeeMe_C) == 0x000008, "Wrong alignment on UTedAch_YouCantSeeMe_C");
static_assert(sizeof(UTedAch_YouCantSeeMe_C) == 0x000070, "Wrong size on UTedAch_YouCantSeeMe_C");

}

