#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TedCmdAbility_SignalDisruption

#include "Basic.hpp"

#include "Tempest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TedCmdAbility_SignalDisruption.TedCmdAbility_SignalDisruption_C
// 0x0000 (0x0590 - 0x0590)
class UTedCmdAbility_SignalDisruption_C final : public UTedPawnCommand_AbilityBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TedCmdAbility_SignalDisruption_C">();
	}
	static class UTedCmdAbility_SignalDisruption_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTedCmdAbility_SignalDisruption_C>();
	}
};
static_assert(alignof(UTedCmdAbility_SignalDisruption_C) == 0x000008, "Wrong alignment on UTedCmdAbility_SignalDisruption_C");
static_assert(sizeof(UTedCmdAbility_SignalDisruption_C) == 0x000590, "Wrong size on UTedCmdAbility_SignalDisruption_C");

}

