#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TedPlayerCmd_GravityManipulators_Debuff

#include "Basic.hpp"

#include "Tempest_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TedPlayerCmd_GravityManipulators_Debuff.TedPlayerCmd_GravityManipulators_Debuff_C
// 0x0000 (0x05C8 - 0x05C8)
class UTedPlayerCmd_GravityManipulators_Debuff_C final : public UTedPlayerCommand_ApplyGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TedPlayerCmd_GravityManipulators_Debuff_C">();
	}
	static class UTedPlayerCmd_GravityManipulators_Debuff_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTedPlayerCmd_GravityManipulators_Debuff_C>();
	}
};
static_assert(alignof(UTedPlayerCmd_GravityManipulators_Debuff_C) == 0x000008, "Wrong alignment on UTedPlayerCmd_GravityManipulators_Debuff_C");
static_assert(sizeof(UTedPlayerCmd_GravityManipulators_Debuff_C) == 0x0005C8, "Wrong size on UTedPlayerCmd_GravityManipulators_Debuff_C");

}

