#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Dialogue

#include "Basic.hpp"

#include "BP_Dialogue_classes.hpp"
#include "BP_Dialogue_parameters.hpp"


namespace SDK
{

// Function BP_Dialogue.BP_Dialogue_C.Action_EndDialogue
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   NextDialogueStage                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FS_Dialogue_EndParameters& Parameters                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::Action_EndDialogue(int32 NextDialogueStage, const struct FS_Dialogue_EndParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "Action_EndDialogue");

	Params::BP_Dialogue_C_Action_EndDialogue Parms{};

	Parms.NextDialogueStage = NextDialogueStage;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue.BP_Dialogue_C.ActivateDialogue
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Dialogue_C::ActivateDialogue()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "ActivateDialogue");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Dialogue.BP_Dialogue_C.CheckForErrors
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class FText>&                    ErrorMessages                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_Dialogue_C::CheckForErrors(TArray<class FText>& ErrorMessages)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "CheckForErrors");

	Params::BP_Dialogue_C_CheckForErrors Parms{};

	Parms.ErrorMessages = std::move(ErrorMessages);

	UObject::ProcessEvent(Func, &Parms);

	ErrorMessages = std::move(Parms.ErrorMessages);

	return Parms.ReturnValue;
}


// Function BP_Dialogue.BP_Dialogue_C.ExecuteUbergraph_BP_Dialogue
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::ExecuteUbergraph_BP_Dialogue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "ExecuteUbergraph_BP_Dialogue");

	Params::BP_Dialogue_C_ExecuteUbergraph_BP_Dialogue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue.BP_Dialogue_C.GetDefaultAudioTriggerForDialogue
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// E_Dialogue_AudioTrigger                 AudioTrigger                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FName*                            AudioTriggerName                                       (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetDefaultAudioTriggerForDialogue(E_Dialogue_AudioTrigger AudioTrigger, class FName* AudioTriggerName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetDefaultAudioTriggerForDialogue");

	Params::BP_Dialogue_C_GetDefaultAudioTriggerForDialogue Parms{};

	Parms.AudioTrigger = AudioTrigger;

	UObject::ProcessEvent(Func, &Parms);

	if (AudioTriggerName != nullptr)
		*AudioTriggerName = Parms.AudioTriggerName;
}


// Function BP_Dialogue.BP_Dialogue_C.GetDialogueParameters
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FS_DialogueParameters*           DialogueParameters                                     (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetDialogueParameters(struct FS_DialogueParameters* DialogueParameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetDialogueParameters");

	Params::BP_Dialogue_C_GetDialogueParameters Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DialogueParameters != nullptr)
		*DialogueParameters = std::move(Parms.DialogueParameters);
}


// Function BP_Dialogue.BP_Dialogue_C.GetDialogueStage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// int32*                                  DialogueStage                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetDialogueStage(int32* DialogueStage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetDialogueStage");

	Params::BP_Dialogue_C_GetDialogueStage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DialogueStage != nullptr)
		*DialogueStage = Parms.DialogueStage;
}


// Function BP_Dialogue.BP_Dialogue_C.GetExternalSpeakerSlots
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<TSoftObjectPtr<class AActor>>*   Actor_Array                                            (Parm, OutParm)

void ABP_Dialogue_C::GetExternalSpeakerSlots(TArray<TSoftObjectPtr<class AActor>>* Actor_Array)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetExternalSpeakerSlots");

	Params::BP_Dialogue_C_GetExternalSpeakerSlots Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Actor_Array != nullptr)
		*Actor_Array = std::move(Parms.Actor_Array);
}


// Function BP_Dialogue.BP_Dialogue_C.GetInterlocutorActor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           ActorClass                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor**                          Interlocutor                                           (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetInterlocutorActor(class UClass* ActorClass, class AActor** Interlocutor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetInterlocutorActor");

	Params::BP_Dialogue_C_GetInterlocutorActor Parms{};

	Parms.ActorClass = ActorClass;

	UObject::ProcessEvent(Func, &Parms);

	if (Interlocutor != nullptr)
		*Interlocutor = Parms.Interlocutor;
}


// Function BP_Dialogue.BP_Dialogue_C.GetPlayerCharacterWorld
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_jRPG_Character_World_C**      AsBP_J_RPG_Character_World                             (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetPlayerCharacterWorld(class ABP_jRPG_Character_World_C** AsBP_J_RPG_Character_World)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetPlayerCharacterWorld");

	Params::BP_Dialogue_C_GetPlayerCharacterWorld Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AsBP_J_RPG_Character_World != nullptr)
		*AsBP_J_RPG_Character_World = Parms.AsBP_J_RPG_Character_World;
}


// Function BP_Dialogue.BP_Dialogue_C.GetSpeakerActor
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UBP_DataAsset_DialogueCharacter_C*Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor**                          Actor                                                  (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::GetSpeakerActor(class UBP_DataAsset_DialogueCharacter_C* Character, class AActor** Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "GetSpeakerActor");

	Params::BP_Dialogue_C_GetSpeakerActor Parms{};

	Parms.Character = Character;

	UObject::ProcessEvent(Func, &Parms);

	if (Actor != nullptr)
		*Actor = Parms.Actor;
}


// Function BP_Dialogue.BP_Dialogue_C.OnEnvelopeFollowerUpdate_Event
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   EnvelopeValue                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::OnEnvelopeFollowerUpdate_Event(float EnvelopeValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "OnEnvelopeFollowerUpdate_Event");

	Params::BP_Dialogue_C_OnEnvelopeFollowerUpdate_Event Parms{};

	Parms.EnvelopeValue = EnvelopeValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue.BP_Dialogue_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Dialogue_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Dialogue.BP_Dialogue_C.ResetNPCAnim
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Dialogue_C::ResetNPCAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "ResetNPCAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Dialogue.BP_Dialogue_C.RestoreBattleParty
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Dialogue_C::RestoreBattleParty()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "RestoreBattleParty");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Dialogue.BP_Dialogue_C.SetBattleParty
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<class UBP_CharacterData_C*>&     CharacterData                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_Dialogue_C::SetBattleParty(TArray<class UBP_CharacterData_C*>& CharacterData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "SetBattleParty");

	Params::BP_Dialogue_C_SetBattleParty Parms{};

	Parms.CharacterData = std::move(CharacterData);

	UObject::ProcessEvent(Func, &Parms);

	CharacterData = std::move(Parms.CharacterData);
}


// Function BP_Dialogue.BP_Dialogue_C.SetDialogueParameters
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FS_DialogueParameters&     DialogueParameters                                     (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::SetDialogueParameters(const struct FS_DialogueParameters& DialogueParameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "SetDialogueParameters");

	Params::BP_Dialogue_C_SetDialogueParameters Parms{};

	Parms.DialogueParameters = std::move(DialogueParameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue.BP_Dialogue_C.SetDialogueStage
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   DialogueStage                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Dialogue_C::SetDialogueStage(int32 DialogueStage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "SetDialogueStage");

	Params::BP_Dialogue_C_SetDialogueStage Parms{};

	Parms.DialogueStage = DialogueStage;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Dialogue.BP_Dialogue_C.StartDialog
// (BlueprintCallable, BlueprintEvent)

void ABP_Dialogue_C::StartDialog()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Dialogue_C", "StartDialog");

	UObject::ProcessEvent(Func, nullptr);
}

}

