#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FunctionLibrary_ConditionCheckerHelpers

#include "Basic.hpp"

#include "BP_FunctionLibrary_ConditionCheckerHelpers_classes.hpp"
#include "BP_FunctionLibrary_ConditionCheckerHelpers_parameters.hpp"


namespace SDK
{

// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.CheckCondition
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FConditionChecker_Wrapper& ConditionCheckerWrapper                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::CheckCondition(const struct FConditionChecker_Wrapper& ConditionCheckerWrapper, class UObject* __WorldContext, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "CheckCondition");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_CheckCondition Parms{};

	Parms.ConditionCheckerWrapper = std::move(ConditionCheckerWrapper);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.CheckOptionalCondition
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FConditionChecker_Wrapper& ConditionCheckerWrapper                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::CheckOptionalCondition(const struct FConditionChecker_Wrapper& ConditionCheckerWrapper, class UObject* __WorldContext, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "CheckOptionalCondition");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_CheckOptionalCondition Parms{};

	Parms.ConditionCheckerWrapper = std::move(ConditionCheckerWrapper);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.IsConditionSet
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// const struct FConditionChecker_Wrapper& ConditionCheckerWrapper                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::IsConditionSet(const struct FConditionChecker_Wrapper& ConditionCheckerWrapper, class UObject* __WorldContext, bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "IsConditionSet");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_IsConditionSet Parms{};

	Parms.ConditionCheckerWrapper = std::move(ConditionCheckerWrapper);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.ValidateCondition
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FConditionChecker_Wrapper& Condition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// TArray<class FText>&                    ErrorMessages                                          (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FString&                          PropertyPath                                           (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::ValidateCondition(const struct FConditionChecker_Wrapper& Condition, TArray<class FText>& ErrorMessages, class FString& PropertyPath, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "ValidateCondition");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_ValidateCondition Parms{};

	Parms.Condition = std::move(Condition);
	Parms.ErrorMessages = std::move(ErrorMessages);
	Parms.PropertyPath = std::move(PropertyPath);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	ErrorMessages = std::move(Parms.ErrorMessages);
	PropertyPath = std::move(Parms.PropertyPath);
}


// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.BindEventOnGameStateChanged
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void()>&                Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const struct FConditionChecker_Wrapper& Condition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::BindEventOnGameStateChanged(const TDelegate<void()>& Event, const struct FConditionChecker_Wrapper& Condition, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "BindEventOnGameStateChanged");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_BindEventOnGameStateChanged Parms{};

	Parms.Event = Event;
	Parms.Condition = std::move(Condition);
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_FunctionLibrary_ConditionCheckerHelpers.BP_FunctionLibrary_ConditionCheckerHelpers_C.UnbindEventOnGameStateChanged
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const TDelegate<void()>&                Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const struct FConditionChecker_Wrapper& Condition                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBP_FunctionLibrary_ConditionCheckerHelpers_C::UnbindEventOnGameStateChanged(const TDelegate<void()>& Event, const struct FConditionChecker_Wrapper& Condition, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_FunctionLibrary_ConditionCheckerHelpers_C", "UnbindEventOnGameStateChanged");

	Params::BP_FunctionLibrary_ConditionCheckerHelpers_C_UnbindEventOnGameStateChanged Parms{};

	Parms.Event = Event;
	Parms.Condition = std::move(Condition);
	Parms.__WorldContext = __WorldContext;

	UObject::ProcessEvent(Func, &Parms);
}

}

