#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ItemFilter_Base

#include "Basic.hpp"

#include "SandFall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ItemFilter_Base.BP_ItemFilter_Base_C
// 0x0000 (0x0028 - 0x0028)
class UBP_ItemFilter_Base_C : public UExtendedObject
{
public:
	void GetCompatibleItemSorters(TArray<class UClass*>* ItemSorters);
	void GetDisplayName(class FText* DisplayName);
	void ExecuteFilter(const TArray<class UBP_ItemInstance_Base_C*>& ItemInstances, TArray<class UBP_ItemInstance_Base_C*>* FilteredItemInstances);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ItemFilter_Base_C">();
	}
	static class UBP_ItemFilter_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_ItemFilter_Base_C>();
	}
};
static_assert(alignof(UBP_ItemFilter_Base_C) == 0x000008, "Wrong alignment on UBP_ItemFilter_Base_C");
static_assert(sizeof(UBP_ItemFilter_Base_C) == 0x000028, "Wrong size on UBP_ItemFilter_Base_C");

}

