#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EInputType

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum EInputType.EInputType
// NumValues: 0x0004
enum class EInputType : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	EInputType_MAX                           = 3,
};

}

