#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Debug_UMG_AnimationDebugger_WidgetEntry

#include "Basic.hpp"

#include "WBP_Debug_UMG_AnimationDebugger_WidgetEntry_classes.hpp"
#include "WBP_Debug_UMG_AnimationDebugger_WidgetEntry_parameters.hpp"


namespace SDK
{

// Function WBP_Debug_UMG_AnimationDebugger_WidgetEntry.WBP_Debug_UMG_AnimationDebugger_WidgetEntry_C.RegisterWidget
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UUserWidget*                      Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<class UWidgetAnimation*>&        Animations                                             (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UWBP_Debug_UMG_AnimationDebugger_WidgetEntry_C::RegisterWidget(class UUserWidget* Widget, TArray<class UWidgetAnimation*>& Animations)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Debug_UMG_AnimationDebugger_WidgetEntry_C", "RegisterWidget");

	Params::WBP_Debug_UMG_AnimationDebugger_WidgetEntry_C_RegisterWidget Parms{};

	Parms.Widget = Widget;
	Parms.Animations = std::move(Animations);

	UObject::ProcessEvent(Func, &Parms);

	Animations = std::move(Parms.Animations);
}

}

