#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HUD_Battle_TargetingControls

#include "Basic.hpp"

#include "WBP_HUD_Battle_TargetingControls_classes.hpp"
#include "WBP_HUD_Battle_TargetingControls_parameters.hpp"


namespace SDK
{

// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.AppearInternal
// (BlueprintCallable, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::AppearInternal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "AppearInternal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.BndEvt__WBP_HUD_Battle_TargetingControls_WBP_GM_PromptGeneric_Back_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_Battle_TargetingControls_C::BndEvt__WBP_HUD_Battle_TargetingControls_WBP_GM_PromptGeneric_Back_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "BndEvt__WBP_HUD_Battle_TargetingControls_WBP_GM_PromptGeneric_Back_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_HUD_Battle_TargetingControls_C_BndEvt__WBP_HUD_Battle_TargetingControls_WBP_GM_PromptGeneric_Back_K2Node_ComponentBoundEvent_2_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.BndEvt__WBP_HUD_CancelButton_WBP_GM_PromptGeneric_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButtonBase*                Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_Battle_TargetingControls_C::BndEvt__WBP_HUD_CancelButton_WBP_GM_PromptGeneric_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature(class UCommonButtonBase* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "BndEvt__WBP_HUD_CancelButton_WBP_GM_PromptGeneric_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature");

	Params::WBP_HUD_Battle_TargetingControls_C_BndEvt__WBP_HUD_CancelButton_WBP_GM_PromptGeneric_K2Node_ComponentBoundEvent_1_CommonButtonBaseClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::BP_OnDeactivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "BP_OnDeactivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.DisappearInternal
// (BlueprintCallable, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::DisappearInternal()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "DisappearInternal");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.ExecuteUbergraph_WBP_HUD_Battle_TargetingControls
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_Battle_TargetingControls_C::ExecuteUbergraph_WBP_HUD_Battle_TargetingControls(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "ExecuteUbergraph_WBP_HUD_Battle_TargetingControls");

	Params::WBP_HUD_Battle_TargetingControls_C_ExecuteUbergraph_WBP_HUD_Battle_TargetingControls Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.GetTiedObject
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject**                         Object                                                 (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_Battle_TargetingControls_C::GetTiedObject(class UObject** Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "GetTiedObject");

	Params::WBP_HUD_Battle_TargetingControls_C_GetTiedObject Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Object != nullptr)
		*Object = Parms.Object;
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.OnUIAction
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::OnUIAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "OnUIAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.OnUINavigationFocus
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UBP_UINavigationFocusEvent_C*FocusEventBP                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_HUD_Battle_TargetingControls_C::OnUINavigationFocus(const class UBP_UINavigationFocusEvent_C* FocusEventBP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "OnUINavigationFocus");

	Params::WBP_HUD_Battle_TargetingControls_C_OnUINavigationFocus Parms{};

	Parms.FocusEventBP = FocusEventBP;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HUD_Battle_TargetingControls.WBP_HUD_Battle_TargetingControls_C.OnUINavigationFocusLost
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_HUD_Battle_TargetingControls_C::OnUINavigationFocusLost()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HUD_Battle_TargetingControls_C", "OnUINavigationFocusLost");

	UObject::ProcessEvent(Func, nullptr);
}

}

