#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Username

#include "Basic.hpp"

#include "BP_Username_classes.hpp"
#include "BP_Username_parameters.hpp"


namespace SDK
{

// Function BP_Username.BP_Username_C.ExecuteUbergraph_BP_Username
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Username_C::ExecuteUbergraph_BP_Username(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Username_C", "ExecuteUbergraph_BP_Username");

	Params::BP_Username_C_ExecuteUbergraph_BP_Username Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Username.BP_Username_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Username_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Username_C", "ReceiveTick");

	Params::BP_Username_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Username.BP_Username_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_Username_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Username_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

